baseURL: "https://iamlaksh1.github.io/site/"
languageCode: en-us
title: Lakshmanan 
theme: PaperMod


permalinks:
  posts: "/:slug"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    FirstParagraph: >
      Welecome to my personal blog.       
      I am Lakshmanan, a Software Engineer, specialized in **GIS**, data science, and open source software development. This blog is a collection of my thoughts, ideas, and experiences. 
    SecondParagraph: >
    
    Title: Lakshmanan 
    Photo: posts/images/lv.png

  socialIcons:
    - name: email
      url: "mailto:laksh.gisprog@gmail.com"
    - name: github
      url: "https://github.com/iamlaksh1"
    - name: twitter
      url: "https://twitter.com/iamlaksh1"
 

menu:
  main:
    - name: Posts
      pageRef: /posts/
      weight: 2  
    - identifier: GitHub
      name: GitHub
      url: "https://github.com/iamlaksh1"
      weight: 5
